name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'sre-task/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'sre-task/**'
  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-test-lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: ./crud-api

    - name: Build API
      run: make build-api
      working-directory: ./crud-api

    - name: Run tests
      run: make test
      working-directory: ./crud-api

    - name: Perform code linting
      run: make lint
      working-directory: ./crud-api

  docker-build-push:
    needs: build-test-lint
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./crud-api
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
        build-args: |
          NODE_ENV=${{ secrets.NODE_ENV }}
        secrets: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
